### ISSUE TITLE
[Question] Why ignoring all backgrounds when colab?

### ISSUE THREAD

**Issue by EnergoStalin** [TavernAI/TavernAI-v1#111]
https://github.com/TavernAI/TavernAI/blob/a8e29b9fa501a3e2a84d44922f5617d3695c11b7/server.js#L809-L816
And even if it's reasonable why listing directory anyway?

**Comment by FunkEngine2023** [comment]
I did this... Not for you, nor because of you, I just did the stuff that needed doing to fix cloud-Tavern.... And you want to avoid running tavern in the cloud by running it locally on your PC. Because it's already hard enough running Kobold-AI by itself, in a Colab, then we went and shoehorned in (with a lot of sleight of hand) a whole Tavern interface into the mix too...

For the record `TavernAI/TavernAIColab` is the repo you want to be pulling when running everything in the cloud. Not the `TavernAI/TavernAI` one, going forward... For now this is my fork of it.

This is still very much WIPcode, but I'll be merging it with `TavernAI/TavernAIColab` main branch this week, it's working pretty rock solidly.  The only hitch right now is the user's avatar won't show up until the second running, because the folders aren't there to put the thing into until the first run, and then on the second run it moves it over.  Settings will be persistent across session snow, so your name, and generation preferences will stick the way you last had them.

And most relevant to this issue ticket.

### **BACKGROUNDS ARE BACK!**

https://colab.research.google.com/github/FunkEngine2023/TavernAIColab/blob/Funk-png/colab/GPU.ipynb

![bgbaq](https://user-images.githubusercontent.com/123712145/229389606-fb04796b-d30c-40bb-99f6-fd642e6c89a8.PNG)
![7 minutes](https://user-images.githubusercontent.com/123712145/229389607-d28a3090-267e-42d4-a7d7-fa409740aaa3.PNG)

Just over 7 minutes from push button to index.html loading in the browser as well now...

You don't have to copy paste the API link anymore, I found ways to just smuggle it right in.  It doesn't disconnect randomly. (I figured out *precisely* what was causing that irritating annoyance every 7-10 minutes...)

Oh, of course it saves characters+chats, pretty sure that's mostly not been an issue, but since it saves the settings and config in drive now, you can do things like pick .png format cards instead of .webp.

https://github.com/FunkEngine2023/TavernAIColab/tree/Funk-png


Feedback is appreciated, just please post it to my repo and I'll try and address it.
