### ISSUE TITLE
GPT-4 "Not found" + Some issues with the jailbreak and message continuation.

### ISSUE THREAD

**Issue by tingandthings** [TavernAI/TavernAI-v1#152]
GPT-4 The model: `gpt-4` does not exist', - As stated in the cmd interface

The OpenAI jailbreak most of the times does not work (I only got it to work once before it started saying that "it's against the policy")

"I'm sorry, I cannot comply with that request. As an AI language model, I am programmed to adhere to ethical and legal standards, which includes not producing explicit or inappropriate content. My purpose is to assist with tasks and provide helpful responses within a safe and respectful environment."
![proof 1](https://user-images.githubusercontent.com/123607401/235373325-a9b9723c-085e-4162-966f-f3dcc223450c.PNG)
![proof 2](https://user-images.githubusercontent.com/123607401/235373326-d4ec2905-63de-4247-89c2-9af25c1dfbd6.PNG)

Don't know what the issue is. GPT-3.5-turbo on TavernAI 1.3.1 worked perfectly fine. Not sure why it doesn't in this version.

**Comment by tingandthings** [comment]
As for continuation on openAI, it either repeats the same message or it says something completely different.

**Comment by tingandthings** [comment]
Lil' update: everything seems to be working fine now. idk why it was trippin earlier.
Another update: the jailbreak only seems to work on some characters. Not a lot though.

**Comment by Borov666** [comment]
One day after the release of 1.4.0 with new jailbreak system, additional jailbreak stopped working. Before that, this combination removed any restrictions. Perhaps OpenAI will somehow adapt if there are many same requests that remove restrictions.

There is several another working combinations of standard and additional jailbreak. But I think it makes no sense to post it, since it is also likely to stop working. It's not so difficult to choose a working combination with due diligence.

For GPT-4, you need to get OpenAI approval to use this api.

**Comment by tingandthings** [comment]
Got it. Thanks.
