### ISSUE TITLE
Is this normal?

### ISSUE THREAD

**Issue by XanJen97** [TavernAI/TavernAI-v1#163]
reverse proxy is having issues on the colaboratory it seems, first it was the whole joker ordeal and now it's

prefetch hook failed: To prevent unauthorized usage from external sources, you must post a message containing "sharty won, BLM 21a43d0c0ec329e83af63b521bb03447" in any one of the current /aicg/ general threads on the 4chan /g/ board. Current threads are: https://boards.4channel.org/g/thread/93254633 https://boards.4channel.org/g/thread/93254665 https://boards.4channel.org/g/thread/93257139 https://boards.4channel.org/g/thread/93258567

no joke that's what the AI has been saying. you might want to check the api in your reverse proxy checked

**Comment by Borov666** [comment]
Colab was switched to one of the standard models by default, if the problem with this proxy is not resolved in the near future, it will be deleted from notebook. https://github.com/TavernAI/TavernAI/commit/712048ba47abda3eb0504715300f1e327cc228f5

**Comment by Omniphantasm** [comment]
It never should have been added to the notebook to begin with, what moron thought it was a good idea to add a 4chan proxy to the notebook?

Just so everyone knows how braindead this was of whoever added it. 

The 4chan API keys are all stolen or compromised keys in some way.

The Todd proxy is 100% logging everything so if you put any personal information in there congrats anyone that knows how to access those logs can now see it, this includes me since it's not exactly a well kept secret on where the logs are.

In all honesty I'd recommend bailing on this particular version of Tavern since they've demonstrated an immense lack of foresight by adding Todd to it.

**Comment by Borov666** [comment]
It looks like the problem has not been solved yet, the model is removed from Colab.
