### ISSUE TITLE
More robust system for truncating generated content (bug/enhancement?)

### ISSUE THREAD

**Issue by dasnullman** [TavernAI/TavernAI-v1#220]
Recently my friend was using TavernAI as a frontend to KoboldAI, and his model generated some content along the lines of this: 

> {USER} : You can stop there if you dislike the direction this conversation is going.

This is weird, and a model issue. But this was displayed. Perhaps because there was actual text afterwards, with no newline.
So changing the system used to truncate the content that the backend AI generates on behalf of the user might be appropriate.

This issue may not be possible to fix without screwing with certain characters. If so, feel free to close this issue.

**Comment by Borov666** [comment]
Now the standard truncation, if no additional settings are enabled, looks like this:
1) the answer is truncated by "{user}:"
2) the answer is truncated by <|endoftext|> token
3) the answer is truncated by `\\end` token for llama similar models

As far as I can see, the problem is that response has "{user} :" instead "{user}:"

**Comment by Qanitanajiyah** [comment]
Can you speak indonesian?

Pada tanggal Kam, 27 Jul 2023 21.33, Borov666 ***@***.***>
menulis:

**Comment by annaryna** [comment]
jelek
