### ISSUE TITLE
I couldn't get a koboldAI link.

### ISSUE THREAD

**Issue by Jiegehu** [TavernAI/TavernAI-v1#229]
![Screenshot_20231006_110910](https://github.com/TavernAI/TavernAI/assets/147121605/2a7213e4-5c6f-4c5d-a92a-24395dcda026)

**Comment by FunkEngine2023** [comment]
Have you been waiting at least 22 minutes for the link? Some versions of KoboldAI are "hanging" during the load for 10-15 minutes. 

Alternatively you can check the pins on discord and get the link to what is essentially a (colab functionality, the TavernAI is still 1.5.1) 1.6.0 RC colab link which has been proven to resolve the exact issue you've just had a few times already.

**Comment by FunkEngine2023** [comment]
![image](https://github.com/TavernAI/TavernAI/assets/123712145/3b841b32-a8ed-4dee-8042-cc333c90c994)
![image](https://github.com/TavernAI/TavernAI/assets/123712145/986c5197-f780-467b-9cb2-09ac936e94fa)

**Comment by FunkEngine2023** [comment]
https://github.com/FunkEngine2023/FunkEngine2023.github.io/blob/Funky_Notebooks/PolishedTurd.ipynb

You (as a mobile user) need to unfold the cells first and tick this box to have it run TavernAI for you in addition to Kobold. collapse the tabs and hit the button under the V that says DO IT!

![image (18)](https://github.com/TavernAI/TavernAI/assets/123712145/b4a7ba45-c37e-48f5-9290-8c0a6aff690a)


If you want a specific particular model, you can load it through the AI menu of KoboldAI,(Pictures below of how to change models.) but out of the box it loads a Pygmalion6b "not banned by colab(yet)" model by default, and if you're used to chatting with Nerys Neribus etc, you'll be pleasantly surprised at the quality of responses.

Otherwise this sheet will load your existing cards and chats off of your Google Drive you don't need to move anything. 
(Just use it instead of GPU.ipynb until 1.6.0 ships and it gets the overhaul it has so long needed.)
You cannot miss your tavernai link at the current time, I made it fairly obvious and easy to find when you scroll up to grab it as KoboldAi loads...
![image (19)](https://github.com/TavernAI/TavernAI/assets/123712145/efcffa29-1548-4d21-ad69-7204a18386b1)



To change a model, open the classic ui in a tab.
![classiclink](https://github.com/TavernAI/TavernAI/assets/123712145/37f2d24a-9414-46ec-953d-42ffb3951090)

hit the menu burger (on mobile) then the AI button.
![image (14)](https://github.com/TavernAI/TavernAI/assets/123712145/df4b57e5-3b54-4b00-b1a8-871b757b4978)

Choose HF Pytorch.
Paste the "name/model-#B" link from HF to your favorite model into the "Huggingface Model Name" box...
(So for Nerybus "KoboldAI/OPT-6.7B-Nerybus-Mix" or Nerys "KoboldAI/OPT-6B-nerys-v2" or Erebus "KoboldAI/OPT-6.7B-Erebus") ![image (15)](https://github.com/TavernAI/TavernAI/assets/123712145/16f3ec12-8801-4c8c-ad78-23e035dbbc30)

Pick 4/8/16 bit quant as appropriate (8 bit on colab for 6B models, 4 bit for 13B models.) and hit load.

![image (16)](https://github.com/TavernAI/TavernAI/assets/123712145/7c6a5212-68d9-4ef4-a29c-b701106107d1)

**Comment by Jiegehu** [comment]
Thank you very much, I will try your method over the weekend!
