### ISSUE TITLE
Downloaded TavernAI, it won't Start

### ISSUE THREAD

**Issue by Persevering-Pug** [TavernAI/TavernAI-v1#244]
I receive two different kinds of errors when I run the Start.bat as either normal and as administrator... I'm very unfamiliar with all of this kind of stuff, so I don't quite understand what the issues are, also I'm running on Windows 10.

Administrator Error:
![Administrator Error](https://github.com/TavernAI/TavernAI/assets/154001257/3361c1bd-d9ef-4ffa-9a16-1c8df3732330)

Non-Administrator Error
![Non-Administrator Error](https://github.com/TavernAI/TavernAI/assets/154001257/ac40c669-12ce-4d8e-9d0f-8adbdac35017)

PS, thank you for taking the time to read, and if you do reply, please put it in really really basic terms for someone with no computer knowledge to understand so I know what the problem is, and what I'm doing, or what I need to do to fix it.

I've also downloaded and installed Node, there were some Warnings and other things that happened... not sure if that's the root of the problem either.

**Comment by nimer-** [comment]
It is because windows ExecutionPolicy for powershell scripts is in default setting set to Restricted. 
Simplest way to get it to work is to run in powershell: 

`Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser` 

And say yes when it asks. Just a reminder, it will lower your protection against malicious scripts somewhat (you can read more about it here: [https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.4#remotesigned](url)). But it is limited to your user account only, so "it is something" :)

Hope it helps.

**Comment by Tenkotataii** [comment]
Actually the fix is simple: open the properties page on the file start.ps1 and unlock it. 
I tried writing commands, but it didnt work.
