### ISSUE TITLE
Enter button

### ISSUE THREAD

**Issue by wowthatscoolig** [TavernAI/TavernAI-v1#246]
When ever I press enter it makes a new line. I went as far as restarting my laptop and redownloading tavern nothing has worked.
Check my comment please.

**Comment by wowthatscoolig** [comment]
Now it just has errors
The funky beats of death 💀 

Error: listen EADDRINUSE: address already in use 127.0.0.1:8000
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at doListen (node:net:2075:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1899:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8000
}

**Comment by FunkEngine2023** [comment]
So let's go for the easy fix first...

I am presuming you are specifically referring to the outgoing message entry field. If we're not on the same page about that, let me know.

What happens when you hold shift and hit return/enter?  The simple fix may be that for whatever reason, the intended behavior is reversed on your system, possibly by a browser extension, etc.

Is this a Windows PC laptop or a MacBook?

If it sends the message with the shift key held down, it would definitely be something on the machine causing it.

Final question before I send this over to you:

You type a message and click the quil feather on the right of the entry field. Does the message send doing that?

--FunkEngine
(Also available in Discord.)
https://discord.com/invite/PYQDDh5U

**Comment by FunkEngine2023** [comment]
> Now it just has errors
> The funky beats of death 💀 
> 
> Error: listen EADDRINUSE: address already in use 127.0.0.1:8000
>     at Server.setupListenHandle [as _listen2] (node:net:1872:16)
>     at listenInCluster (node:net:1920:12)
>     at doListen (node:net:2075:7)
>     at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
> Emitted 'error' event on Server instance at:
>     at emitErrorNT (node:net:1899:8)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
>   code: 'EADDRINUSE',
>   errno: -4091,
>   syscall: 'listen',
>   address: '127.0.0.1',
>   port: 8000
> }

You can only run one copy of TavernAI per port. That error text says that you still have a TavernAI console session running on your machine and tried to run another.

Task manager for node.exe, and you can kill the process.
