### ISSUE TITLE
[Feature Request] Support for mobile phone

### ISSUE THREAD

**Issue by Silver267** [TavernAI/TavernAI-v1#34]
If possible, can TavernAI implement some sort of support for phones? Currently the webpage looks weird on phones, and optimizing it would benefit many users who are using colab or kaggle on phone.

**Comment by kimoVoid** [comment]
Additionally one of the biggest issues I have while using the page on mobile is the fact that enter doesn't make a new line, it sends the message. Hopefully this gets fixed too.

**Comment by RossAscends** [comment]
> If possible, can TavernAI implement some sort of support for phones? Currently the webpage looks weird on phones, and optimizing it would benefit many users who are using colab or kaggle on phone.

@Silver267 : Upcoming CSS changes will fix this.

> Additionally one of the biggest issues I have while using the page on mobile is the fact that enter doesn't make a new line, it sends the message. Hopefully this gets fixed too. 

@kimovoid : One option would be to reverse the function so pressing enter adds a new line to the input box, and PC users would then need to press shift+enter to send the prompt to the AI. 

(Upcoming changes will have ctrl+enter bound as a hotkey for auto-regenerate last message from AI). 

Since mobile phones don't have a shift/ctrl button, mobile users would have to tap the 'send' button to send the prompt. 

@TavernAI - This is currently how CAI handles things. Thoughts?

**Comment by scythe000** [comment]
Looking forward to this also

**Comment by Slug-Cat** [comment]
The edit button and other buttons are also impractically tiny on mobile

**Comment by Cathie-486** [comment]
I would mainly love to be able to just use tavern ai on mobile without collab due to collab having limited connections

**Comment by FunkEngine2023** [comment]
I did this... Not for you, nor because of you, I just did the stuff that needed doing to fix cloud-Tavern...

And you want to avoid running TavernAI in the cloud where all possible running it locally on your PC. 

It's already hard enough running Kobold-AI by itself, in a Colab, then we went and shoehorned in (with a lot of sleight of hand) a whole Tavern interface into the mix too...

For the record `TavernAI/TavernAIColab` is the repo you want to be pulling when running everything in the cloud. Not the `TavernAI/TavernAI` one, going forward... For now this is my fork of it.

This is still very much WIPcode, but I'll be merging it with `TavernAI/TavernAIColab` main branch this week, it's working pretty rock solidly.  The only hitch right now is the user's avatar won't show up until the second running, because the folders aren't there to put the thing into until the first run, and then on the second run it moves it over.  Settings will be persistent across session snow, so your name, and generation preferences will stick the way you last had them.

And most relevant to recent grumblings...

###  __**BACKGROUNDS ARE BACK!**__

https://colab.research.google.com/github/FunkEngine2023/TavernAIColab/blob/Funk-png/colab/GPU.ipynb

![bgbaq](https://user-images.githubusercontent.com/123712145/229389606-fb04796b-d30c-40bb-99f6-fd642e6c89a8.PNG)
![7 minutes](https://user-images.githubusercontent.com/123712145/229389607-d28a3090-267e-42d4-a7d7-fa409740aaa3.PNG)

Just over 7 minutes from push button to index.html loading in the browser as well now...

You don't have to copy paste the API link anymore, I found ways to just smuggle it right in.  It doesn't disconnect randomly. (I figured out *precisely* what was causing that irritating annoyance every 7-10 minutes...)

Oh, of course it saves characters+chats, pretty sure that's mostly not been an issue, but since it saves the settings and config in drive now, you can do things like pick .png format cards instead of .webp.

https://github.com/FunkEngine2023/TavernAIColab/tree/Funk-png


Feedback is appreciated, just please post it to my repo and I'll try and address it.

**Comment by FunkEngine2023** [comment]
> I would mainly love to be able to just use tavern ai on mobile without collab due to collab having limited connections

You are aware of just how much electricity the Colab running your Ai is sucking up per hour... Right?  If you **tried** to run the AI in the phone the phone would rapidly make crispy fried chicken out of youur hands...

For the next few years expect to either pay for someone else to run the AI for you, or slum it on Colab with the rest of us...

Things may get worse before they get better.

 :)

**Comment by Slug-Cat** [comment]
> > I would mainly love to be able to just use tavern ai on mobile without collab due to collab having limited connections
> 
> You are aware of just how much electricity the Colab running your Ai is sucking up per hour... Right? If you **tried** to run the AI in the phone the phone would rapidly make crispy fried chicken out of youur hands...
> 
> For the next few years expect to either pay for someone else to run the AI for you, or slum it on Colab with the rest of us...
> 
> Things may get worse before they get better.
> 
> :)

They may be referring to running an instance of KoboldAI on a desktop, and having a dedicated TavernAI client for mobile to access whatever API externally.

**Comment by FunkEngine2023** [comment]
> > > I would mainly love to be able to just use tavern ai on mobile without collab due to collab having limited connections
> > 
> > 
> > You are aware of just how much electricity the Colab running your Ai is sucking up per hour... Right? If you **tried** to run the AI in the phone the phone would rapidly make crispy fried chicken out of youur hands...
> > For the next few years expect to either pay for someone else to run the AI for you, or slum it on Colab with the rest of us...
> > Things may get worse before they get better.
> > :)
> 
> They may be referring to running an instance of KoboldAI on a desktop, and having a dedicated TavernAI client for mobile to access whatever API externally.

I run my KoboldAI about 600 miles away, The Tavern on an old laptop in my basement, and do the actual interaction via an old android wifi tablet...  Way cheaper than buying my own pair of GPUs to run locally.

Related to just a mobile tavern... Cohee's fork __allegedly__ will build on android ARM because it uses an entirely java based image manipulation library, whereas we're still sort of lashed to the anchor of sharp/libvips yet still.  He hasn't tried it himself but several people have said they were able to get it going once they managed to sideload nodejs on their phones...

**Comment by FunkEngine2023** [comment]
https://rentry.org/TAI_Termux
![image](https://user-images.githubusercontent.com/123712145/229399982-8159fe99-8e43-4802-ba14-0af5a8f38c79.png)
![image](https://user-images.githubusercontent.com/123712145/229400083-9315f59c-2281-4b0d-8a20-bc1747336054.png)
![image](https://user-images.githubusercontent.com/123712145/229400113-934d7261-a91b-4ca8-8051-f5b0f01703ad.png)
