### ISSUE TITLE
Massive security issue.

### ISSUE THREAD

**Issue by xoucers** [TavernAI/TavernAI-v1#40]
Too many to list...

Example:
https://github.com/Nameless9000/TavernAIPwn

**Comment by out-of-phaze** [comment]
Okay, since apparently three is too many to list, here's what someone got from a brief look at the repo:
> 1) The error page for TavernAI lists the path of the script causing the error, from which a path to the root dir can be derived
> 2) The web server(?????) will GET any path it's given
> 3) The delete character request will take any path it's given

My own addendum to #2: When using the /backgrounds route, and possibly others.

Anyway, validating paths (after `.` and `..` resolution) to make sure they're within the root directory seems like a simple solution to some of these.

**Comment by TavernAI** [comment]
Planned solution:
1) Whitelist of ip addresses for server.js functions.
2) localhost is whitelisted by default.
3) Ability to disable-enable the whitelist

**Comment by Borov666** [comment]
Security update: https://github.com/TavernAI/TavernAI/commit/0a13b2da5339af33cf602de5d2feef2386608a6d
